# Generated by Django 2.0.1 on 2018-01-20 15:23

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers, (, ), -, +, and spaces are allowed.', regex='^[0-9\\-\\(\\) \\+]+$'), app.models.integers_validator])),
                ('my_property_type', models.CharField(choices=[('S', 'Single Family'), ('H', 'Highrise Condo'), ('T', 'Townhouse')], max_length=1)),
                ('notes', models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10, message='Notes must consist of at least 10 characters.')])),
            ],
        ),
    ]
